name: NetEase OpenSource
title: NetEase OpenSource
org: NetEase.com, Inc.
author: Zhong Jianxin
redcarpet:
  :lax_spacing: true
profiles:
  development:
    base_url: ''
    #slim:
    #http://rdoc.info/gems/slim/file/README.md#Available_options
    #  :sort_attrs: false
    #  :pretty: true
  production:
    base_url: http://code.netease.com
nav:
  - /projects/
  - /authors/
  - /news/
